apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sensor-server
  namespace: openshift-gitops
spec:
  destination:
    namespace: '*'
    server: 'https://kubernetes.default.svc'
  project: gitops-workshop
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: ArgoCD/Manifests
    repoURL: 'https://github.com/rhilconsultants/GitOps.git'
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
  - group: apps
    kind: Route
    jsonPointers:
    - /spec/host
  - group: apps
    kind: Service
    jsonPointers:
    - /spec/clusterIPs
  - group: apps
    kind: Service
    jsonPointers:
    - /spec/clusterIP
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas