project: gitops-workshop
source:
  repoURL: 'https://github.com/rhilconsultants/GitOps.git'
  path: ArgoCD/Manifests
  targetRevision: main
  directory:
    recurse: true
    jsonnet: {}
destination:
  server: 'https://kubernetes.default.svc'
  namespace: '*'
syncPolicy:
  automated:
    prune: true
    selfHeal: true
