apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  labels:
    app.kubernetes.io/instance: sensor-app-build
    app.kubernetes.io/name: sensor-app-build
    pipeline.openshift.io/strategy: docker
    pipeline.openshift.io/type: kubernetes
  name: sensor-app-build
  namespace: sensor-app
spec:
  finally:
    - name: openshift-client
      params:
        - name: SCRIPT
          value: oc rollout restart deployment/sensor-app-server
        - name: VERSION
          value: latest
      taskRef:
        kind: ClusterTask
        name: openshift-client
      workspaces:
        - name: kubeconfig-dir
          workspace: workspace
        - name: manifest-dir
          workspace: workspace
  params:
    - default: sensor-app-server
      name: APP_NAME
      type: string
    - default: 'https://github.com/rhilconsultants/GitOps.git'
      name: GIT_REPO
      type: string
    - default: main
      name: GIT_REVISION
      type: string
    - default: quay.io/thason/sensor-app
      name: IMAGE_NAME
      type: string
    - default: .\sensor-application
      name: PATH_CONTEXT
      type: string
    - default: latest
      name: IMAGE_TAG
      type: string
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: deleteExisting
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8:v1.7.2-11
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace
    - name: build
      params:
        - name: IMAGE
          value: '$(params.IMAGE_NAME):$(params.IMAGE_TAG)'
        - name: TLSVERIFY
          value: 'false'
        - name: CONTEXT
          value: $(params.PATH_CONTEXT)
        - name: DOCKERFILE
          value: ContainerFile
        - name: FORMAT
          value: docker
        - name: BUILDER_IMAGE
          value: 'registry.access.redhat.com/ubi8/buildah:latest'
      runAfter:
        - fetch-repository
      taskRef:
        kind: ClusterTask
        name: build-n-push
      workspaces:
        - name: source
          workspace: workspace
  workspaces:
    - name: workspace