kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: workspace
  namespace: nodejs-demo
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: pv0014
  volumeMode: Filesystem

