kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta2
metadata:
  name: sensor-hpa
  namespace: sensor-app
spec:
  scaleTargetRef:
    kind: Deployment
    name: sensor-app-server
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
