FROM registry.access.redhat.com/ubi8/nodejs-16:latest

# Create app directory
WORKDIR /tmp

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY sensor-application/package*.json ./


# update the base image
RUN npm install && npm audit fix
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY /sensor-application .

EXPOSE 8081
CMD [ "node", "server.js" ]